# Generated by Django 4.1 on 2023-08-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('mobile_number', models.CharField(max_length=16)),
                ('file_location', models.CharField(max_length=1024)),
            ],
        ),
    ]
